# bazel run //junk:test
py_binary (
    name = "test",
    srcs = ["test.py"],
    main = "test.py",
    deps = [
        "//src:transformation",
        # "@pip//:pytest",
        # "@pip//numpy",
        # "@pip//scipy",
    ],
)